In [29]:
import tensorflow as tf
import numpy as np

### Data Container
- list
- np.array
- tf.Tensor

### What's Tensor
- scalar: 1.1 标量， dim=0
- vector: [1.1], [1.1, 2.2]  向量，dim=1，一维
- matrix: [[1.1, 2.2], [3.3, 4.4]]  矩阵，dim=2，二维
- tensor: rank > 2

统一为tensor

Tensor Flow：Tensor经过运算，在网络上流动

### TF is a computing lib
- int, float, double
- bool
- string

### Create

In [6]:
tf.constant(1)  # 不用理解为常量，1.0沿用的名称，理解为tensor即可

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [5]:
tf.constant(1.)

<tf.Tensor: shape=(), dtype=float32, numpy=1.0>

In [7]:
tf.constant(2.2, dtype=int32)

NameError: name 'int32' is not defined

In [8]:
tf.constant(2., dtype=tf.double)

<tf.Tensor: shape=(), dtype=float64, numpy=2.0>

In [9]:
tf.constant([True, False])

<tf.Tensor: shape=(2,), dtype=bool, numpy=array([ True, False])>

In [10]:
tf.constant('hello')

<tf.Tensor: shape=(), dtype=string, numpy=b'hello'>

### Tensor Property

In [16]:
with tf.device('cpu'):
    a = tf.constant([1])
a

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([1], dtype=int32)>

In [17]:
with tf.device('gpu'):
    b = tf.range(4)
b

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([0, 1, 2, 3], dtype=int32)>

In [18]:
a.device

'/job:localhost/replica:0/task:0/device:CPU:0'

In [19]:
b.device

'/job:localhost/replica:0/task:0/device:CPU:0'

In [23]:
a.gpu()

Instructions for updating:
Use tf.identity instead.


RuntimeError: GPU:0 unknown device.

In [22]:
b.cpu()

Instructions for updating:
Use tf.identity instead.


<tf.Tensor: shape=(4,), dtype=int32, numpy=array([0, 1, 2, 3], dtype=int32)>

In [24]:
b.numpy()  # 转成numpy

array([0, 1, 2, 3], dtype=int32)

In [25]:
b.ndim  # 看多少维

1

In [26]:
tf.rank(b)  # 看shark

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [27]:
tf.rank(tf.ones([3,4,2]))

<tf.Tensor: shape=(), dtype=int32, numpy=3>

### Check Tensor Type
判断是否Tensor类型

In [30]:
a = tf.constant([1.])
b = tf.constant([True, False])
c = tf.constant('hello')
d = np.arange(4)

In [31]:
isinstance(a, tf.Tensor)

True

In [32]:
tf.is_tensor(b)

True

In [33]:
tf.is_tensor(d)

False

In [35]:
a.dtype, b.dtype, c.dtype, d.dtype

(tf.float32, tf.bool, tf.string, dtype('int64'))

In [37]:
a.dtype == tf.float32

True

In [38]:
c.dtype == tf.string

True

### Convert
类型转换

In [40]:
a = np.arange(5)
a.dtype

dtype('int64')

In [42]:
aa = tf.convert_to_tensor(a)
aa

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([0, 1, 2, 3, 4])>

In [43]:
aa = tf.convert_to_tensor(a, dtype=tf.int32)

In [44]:
tf.cast(aa, dtype=tf.float32)

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([0., 1., 2., 3., 4.], dtype=float32)>

In [46]:
aaa = tf.cast(aa, dtype=tf.double)
aaa

<tf.Tensor: shape=(5,), dtype=float64, numpy=array([0., 1., 2., 3., 4.])>

In [48]:
tf.cast(aa, dtype=tf.int32)  # 双精度浮点型转成整型

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 1, 2, 3, 4], dtype=int32)>

### bool <> int

In [49]:
b = tf.constant([0,1])

In [50]:
tf.cast(b, dtype=tf.bool)

<tf.Tensor: shape=(2,), dtype=bool, numpy=array([False,  True])>

In [51]:
bb = tf.cast(b, dtype=tf.bool)
tf.cast(bb, tf.int32)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([0, 1], dtype=int32)>

### tf.Variable
专门针对可以优化的参数

y = wx + b, 这里的w和b是要被梯度优化的参数 

w = tf.Variable(w)

w本身是Tensor，包了一层，仍是Tensor，表示可求导，可训练，需要梯度信息

In [52]:
a = tf.range(5)
a

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 1, 2, 3, 4], dtype=int32)>

In [55]:
b = tf.Variable(a)
b.dtype, b.name

(tf.int32, 'Variable:0')

In [57]:
b = tf.Variable(a, name='input_data')
b.name, b.trainable  # 名字是1.0的概念，一般不用； 可训练的

('input_data:0', True)

In [59]:
isinstance(b, tf.Tensor), isinstance(b, tf.Variable)

(False, True)

In [62]:
tf.is_tensor(b)  # 不推荐用isinstance

True

In [63]:
b.numpy()

array([0, 1, 2, 3, 4], dtype=int32)

### To numpy

In [64]:
a.numpy()

array([0, 1, 2, 3, 4], dtype=int32)

In [65]:
b.numpy()

array([0, 1, 2, 3, 4], dtype=int32)

In [66]:
a = tf.ones([])

In [67]:
a.numpy()

1.0

In [70]:
int(a)  # 这样转，a必须是Scalar（标量），其他类型的Tensor不行

1

In [71]:
float(a)  # 这样转，a必须是Scalar（标量），其他类型的Tensor不行

1.0