In [69]:
import tensorflow as tf
import numpy as np
from tensorflow import keras
from tensorflow.keras import layers

### From Numpy, List

In [2]:
tf.convert_to_tensor(np.ones([2,3]))

<tf.Tensor: shape=(2, 3), dtype=float64, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]])>

In [3]:
tf.convert_to_tensor(np.zeros([2,3]))

<tf.Tensor: shape=(2, 3), dtype=float64, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]])>

In [4]:
tf.convert_to_tensor([1,2])

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [5]:
tf.convert_to_tensor([1,2.])

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 2.], dtype=float32)>

In [6]:
tf.convert_to_tensor([[1],[2.]])

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[1.],
       [2.]], dtype=float32)>

### tf.zeros
全部初始化为0

In [7]:
tf.zeros([])

<tf.Tensor: shape=(), dtype=float32, numpy=0.0>

In [8]:
tf.zeros([1])

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.], dtype=float32)>

In [9]:
tf.zeros([2,2])

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>

In [10]:
tf.zeros([2,3,3])

<tf.Tensor: shape=(2, 3, 3), dtype=float32, numpy=
array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]], dtype=float32)>

### tf.zeros_like
初始化为与某tensor同shape全为0的

In [11]:
a = tf.zeros([2,3,4])

In [12]:
tf.zeros_like(a)

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float32)>

In [13]:
tf.zeros(a.shape)

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float32)>

### tf.ones
全部初始化为1

In [14]:
tf.ones(1)

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([1.], dtype=float32)>

In [15]:
tf.ones([])

<tf.Tensor: shape=(), dtype=float32, numpy=1.0>

In [16]:
tf.ones([2])

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 1.], dtype=float32)>

In [17]:
tf.ones([2,3])

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [18]:
tf.ones_like(a)

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)>

### Fill
全部初始化为某值

In [19]:
tf.fill([2,2], 0)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[0, 0],
       [0, 0]], dtype=int32)>

In [20]:
tf.fill([2,2], 0.)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>

In [21]:
tf.fill([2,2], 1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 1],
       [1, 1]], dtype=int32)>

In [22]:
tf.fill([2,2], 9)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[9, 9],
       [9, 9]], dtype=int32)>

### Normal
随机正态分布中采样

In [23]:
tf.random.normal([2,2], mean=1, stddev=1)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1.0184058, 1.4321252],
       [1.8003876, 1.62186  ]], dtype=float32)>

In [24]:
tf.random.normal([2,2])

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.9548709 , -1.4233096 ],
       [ 0.22374316, -2.2311935 ]], dtype=float32)>

截断的随机正态分布

In [25]:
tf.random.truncated_normal([2,2], mean=0, stddev=1)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.84583324, -0.7233468 ],
       [-1.1292493 , -1.740394  ]], dtype=float32)>

### Uniform
随机均匀分布中采样

In [26]:
tf.random.uniform([2,2], minval=0, maxval=1)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.62436235, 0.3201301 ],
       [0.35767794, 0.5208937 ]], dtype=float32)>

In [27]:
tf.random.uniform([2,2], minval=0, maxval=100)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[39.53595 , 86.50863 ],
       [77.67111 , 16.213799]], dtype=float32)>

### Random Permutation
随机打散, shuffle

In [28]:
idx = tf.range(10)
idx

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [29]:
idx = tf.random.shuffle(idx)  # 随机打散
idx

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([4, 0, 2, 5, 7, 6, 3, 1, 9, 8], dtype=int32)>

In [30]:
a = tf.random.normal([10, 784])
b = tf.random.uniform([10], maxval=10, dtype=tf.int32)
b

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([3, 4, 0, 3, 4, 6, 4, 0, 8, 2], dtype=int32)>

In [31]:
# 一一对应取到打散后的a和b
a = tf.gather(a, idx)
b = tf.gather(b, idx)
b

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([4, 3, 0, 6, 0, 4, 3, 4, 2, 8], dtype=int32)>

### tf.constant
标量

In [32]:
tf.constant(1)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [33]:
tf.constant([1])

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([1], dtype=int32)>

In [34]:
tf.constant([1,2.])

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 2.], dtype=float32)>

In [35]:
tf.constant([[1,2.],[3.]])  # 每行元素个数必要一致

ValueError: Can't convert non-rectangular Python sequence to Tensor.

### Scalar
- []，空括号的shape，表示一个Scalar，典型的应用如loss
- loss = mse(out, y)
- accuracy

loss与accuracy都是标量，就是具体数值

### Loss

In [36]:
out = tf.random.uniform([4,10])
out

<tf.Tensor: shape=(4, 10), dtype=float32, numpy=
array([[0.47809136, 0.5952097 , 0.8011824 , 0.37398338, 0.974241  ,
        0.06121886, 0.0352031 , 0.15239847, 0.1807195 , 0.33194447],
       [0.97978365, 0.582881  , 0.05845296, 0.83796763, 0.10656965,
        0.7944516 , 0.34806657, 0.1761657 , 0.6974777 , 0.19779658],
       [0.03740621, 0.9898832 , 0.9893081 , 0.6989492 , 0.22085798,
        0.46065402, 0.4486004 , 0.9602858 , 0.40171027, 0.7624881 ],
       [0.25419295, 0.08865726, 0.8196044 , 0.62286806, 0.19302833,
        0.05138338, 0.7407185 , 0.10039496, 0.77612805, 0.46042323]],
      dtype=float32)>

In [37]:
y = tf.range(4)
y

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([0, 1, 2, 3], dtype=int32)>

In [38]:
y = tf.one_hot(y, depth=10)
y

<tf.Tensor: shape=(4, 10), dtype=float32, numpy=
array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [39]:
loss = tf.keras.losses.mse(y, out)  # mse：(y - out)平方，再求和
loss

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([0.25286245, 0.31598645, 0.35970432, 0.22994614], dtype=float32)>

In [41]:
loss = tf.reduce_mean(loss)  # loss / 样本个数4
loss

<tf.Tensor: shape=(), dtype=float32, numpy=0.28962484>

### Vector
向量 dim为1
- Bias
 - [out_dim]

x@w+b, 这里的b就是一个vector

In [54]:
net = layers.Dense(10)
net.build((4,8))
net.kernel

<tf.Variable 'kernel:0' shape=(8, 10) dtype=float32, numpy=
array([[-1.0235688e-01, -5.2988666e-01,  4.0034300e-01, -1.0584441e-01,
         8.2964897e-03, -3.2638669e-01, -1.9582084e-01, -1.7525730e-01,
         3.0720323e-01,  3.2224834e-01],
       [-1.6029847e-01, -3.5928777e-01,  2.6531243e-01,  5.3958738e-01,
        -2.4403656e-01, -3.1918672e-01,  2.1162981e-01, -1.7568359e-01,
         3.5229826e-01, -2.9828167e-01],
       [ 1.1530036e-01, -8.4505886e-02, -1.6188985e-01,  2.1279216e-02,
        -4.5943260e-01,  4.6224380e-01, -3.8826221e-01, -5.6504250e-02,
         9.9920630e-03,  6.7657232e-04],
       [ 4.6368206e-01, -3.0797753e-01, -4.5958996e-01,  1.7096984e-01,
         3.4139836e-01, -4.7526014e-01, -4.4895682e-01,  2.6429904e-01,
         3.1793946e-01,  9.3247533e-02],
       [-7.0917249e-02, -2.3401761e-01, -3.9788830e-01, -2.6053843e-01,
        -4.2648405e-01,  4.6792316e-01, -1.5348393e-01, -4.4077718e-01,
         2.2060901e-01,  5.4580784e-01],
       [-4.3343

In [55]:
net.bias # b的shape

<tf.Variable 'bias:0' shape=(10,) dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>

### Matrix
矩阵
dim为2, 即2维

示例：
- input x: [b, vec_dim]， 如：[b, 784]，b张照片
- weight: [input_dim, output_dim]，如：w [8, 10]

理解：多行多列，4张照片，4个，每行784个像素点（单元格）

In [56]:
x = tf.random.normal([4, 784])  # 4张照片
x.shape

TensorShape([4, 784])

In [57]:
net = layers.Dense(10)  # 784 -> 10
net.build((4, 784))
net(x).shape

TensorShape([4, 10])

In [58]:
net.kernel.shape  # w的shape

TensorShape([784, 10])

In [60]:
net.bias  # b的shape

<tf.Variable 'bias:0' shape=(10,) dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>

### Dim=3 Tensor
3维
在自然语言处理（NLP）中用得很广泛
示例：
x: [b, seq_len, word_dim],  
如：[b, 80, 5]，b个句子，每个句子80个单词，每个单词编码长度为5

In [61]:
# imdb电影评论的数据集
(x_train, y_train), (x_test, y_test) = keras.datasets.imdb.load_data(num_words=10000)

In [64]:
x_train = keras.preprocessing.sequence.pad_sequences(x_train, maxlen=80)
x_train.shape  # 25000个人评价，每个评价80个单词

(25000, 80)

In [65]:
emb = embedding(x_train)
emb.shape  # （25000， 80， 100）每个单词编码长度100

NameError: name 'embedding' is not defined

In [ ]:
out = rnn(emb[:4])
out.shape  # (4, 256)

### Dim=4 Tensor
4维
示例：

- Image: [b, h, w, 3]， 如： 【b, 28, 28, 3】, b张图片，高28， 宽28， 3种颜色（RGB）
- feature maps: [b, h, w, c]

In [74]:
x = tf.random.normal((4, 32, 32, 3))

In [75]:
net = layers.Conv2D(16, kernel_size=3)  # 卷积层

In [78]:
net(x)  # shape为(4, 30, 30, 16), 长宽比没有改变，但channel为3变成16了

<tf.Tensor: shape=(4, 30, 30, 16), dtype=float32, numpy=
array([[[[ 6.09420061e-01,  6.01881623e-01, -9.96427760e-02, ...,
          -6.67118669e-01,  1.09667957e+00, -4.68863517e-01],
         [-4.22077537e-01,  7.44081557e-01,  2.25839809e-01, ...,
          -2.65523255e-01,  9.58567798e-01, -2.89709151e-01],
         [ 5.29460423e-02, -6.70375109e-01,  6.99572325e-01, ...,
           7.99767748e-02,  5.09350784e-02,  9.47182238e-01],
         ...,
         [-3.71488929e-01, -7.82385543e-02,  3.87075454e-01, ...,
          -5.75514495e-01,  3.35612088e-01,  2.89113760e-01],
         [ 1.54310897e-01, -6.13941789e-01, -9.93910372e-01, ...,
           8.77744079e-01, -3.75775814e-01, -6.24302030e-02],
         [-7.44941980e-02,  7.71007299e-01,  3.39731693e-01, ...,
          -5.36737815e-02,  2.34903932e-01, -1.66384950e-01]],

        [[-4.48333830e-01, -6.74905241e-01, -1.41872600e-01, ...,
           3.49763215e-01, -4.78808969e-01, -3.07176620e-01],
         [-1.29742771e-01, -1.5

### Dim=5 Tensor
- Single task: [b, h, w, 3]
- meta-learning
 - [task_b, b, h, w, 3]， 理解，分成多个任务去处理4维的