In [1]:
import tensorflow as tf

### tf.norm
Here talks about Vector Norm

In [2]:
a = tf.ones([2,2])
tf.norm(a)

<tf.Tensor: shape=(), dtype=float32, numpy=2.0>

In [4]:
# sqrt平方根(开平方)，square平方
tf.sqrt(tf.reduce_sum(tf.square(a)))

<tf.Tensor: shape=(), dtype=float32, numpy=2.0>

In [6]:
a = tf.ones([4,28,28,3])
tf.norm(a)

<tf.Tensor: shape=(), dtype=float32, numpy=96.99484>

In [7]:
tf.sqrt(tf.reduce_sum(tf.square(a)))

<tf.Tensor: shape=(), dtype=float32, numpy=96.99484>

### L1 Norm

In [8]:
b = tf.ones([2,2])
tf.norm(b)

<tf.Tensor: shape=(), dtype=float32, numpy=2.0>

In [9]:
tf.norm(b, ord=1)

<tf.Tensor: shape=(), dtype=float32, numpy=4.0>

In [10]:
tf.norm(b, ord=1, axis=0)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2., 2.], dtype=float32)>

In [12]:
tf.norm(b, ord=1, axis=1)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2., 2.], dtype=float32)>

In [ ]:
TODO 未完