In [1]:
import tensorflow as tf

### Sort, argsort

In [2]:
a = tf.random.shuffle(tf.range(5))    # 随机打乱
a

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([4, 2, 1, 3, 0], dtype=int32)>

In [3]:
tf.sort(a, direction='DESCENDING')    # 降序排列                           

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([4, 3, 2, 1, 0], dtype=int32)>

In [5]:
idx = tf.argsort(a, direction='DESCENDING')    # 最大值、次大值。。。依次类推所在的索引                             
idx

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 3, 1, 2, 4], dtype=int32)>

In [6]:
tf.gather(a,idx)    # 按索引收集，这里跟降序排列效果相同                                             

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([4, 3, 2, 1, 0], dtype=int32)>

二维的情况
理解：对末一个维度进行排序

In [7]:
a = tf.random.uniform([3,3], maxval=10, dtype=tf.int32)     
a

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[5, 8, 5],
       [4, 4, 6],
       [6, 3, 7]], dtype=int32)>

In [9]:
tf.sort(a)    # （对最末一个维度）顺序排列

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[5, 5, 8],
       [4, 4, 6],
       [3, 6, 7]], dtype=int32)>

In [10]:
tf.sort(a, direction='DESCENDING')   # （对最末一个维度）降序排列                                   

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[8, 5, 5],
       [6, 4, 4],
       [7, 6, 3]], dtype=int32)>

In [12]:
idx = tf.argsort(a)   # （末一个维度上）最大值、次大值。。。的索引
idx

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 2, 1],
       [0, 1, 2],
       [1, 0, 2]], dtype=int32)>

### Top_k

In [15]:
a = tf.random.uniform([3,3], maxval=10, dtype=tf.int32)     
a

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[7, 5, 9],
       [2, 5, 3],
       [9, 4, 0]], dtype=int32)>

In [17]:
res = tf.math.top_k(a, 2)    # Top 2个
res

TopKV2(values=<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[9, 7],
       [5, 3],
       [9, 4]], dtype=int32)>, indices=<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[2, 0],
       [1, 2],
       [0, 1]], dtype=int32)>)

In [18]:
res.indices      # 取得索引                                                      

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[2, 0],
       [1, 2],
       [0, 1]], dtype=int32)>

In [19]:
res.values        # 取得值                                                   

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[9, 7],
       [5, 3],
       [9, 4]], dtype=int32)>

### Top-k accuracy(精确率)

- Prob: [0.1, 0.2, 0.3, 0.4].   # 预测这几种可能的概率
- Label: [2]   # 真实Label是第3种(即index=2,上面0.3可能性那个)
- Onlyn consider top-1 prediction: [3].    # 第四个可能(即index=3,即上面0.4可能性那个)  ---》 0%
- Onlyn consider top-1 prediction: [3, 2]。 ---》 100% （因为真实Label是因为）
- Onlyn consider top-1 prediction: [3, 2, 1]。 ---》100%

TODO： 	示例代码