In [1]:
import tensorflow as tf

### clip_by_value

In [2]:
a = tf.range(10)
a

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [3]:
tf.maximum(a, 2)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([2, 2, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [4]:
tf.minimum(a,8)                                                                                       

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 8], dtype=int32)>

In [5]:
tf.clip_by_value(a, 2, 8)  

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([2, 2, 2, 3, 4, 5, 6, 7, 8, 8], dtype=int32)>

### relu

In [6]:
a = a - 5      
a

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4], dtype=int32)>

In [7]:
tf.nn.relu(a)                                                                                  

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 0, 0, 0, 0, 0, 1, 2, 3, 4], dtype=int32)>

### clip_by_norm

```python
def clip_by_norm(t, clip_norm, axes=None, name=None)
```

> 理解：将传入的梯度张量`t`的L2范数进行了上限约束，约束值即为`clip_norm`，如果`t`的L2范数超过了`clip_norm`，则变换为`t * clip_norm / l2norm(t)`，如此一来，变换后的`t`的L2范数便小于等于`clip_norm`了。

> 理解：向量等比例放缩，方向不变，只改变向量的模

In [10]:
a = tf.random.normal([2,2], mean=10)    
a

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 9.915238, 10.677957],
       [10.341352,  9.877566]], dtype=float32)>

In [11]:
tf.norm(a)                                                                                     

<tf.Tensor: shape=(), dtype=float32, numpy=20.416676>

In [13]:
aa = tf.clip_by_norm(a, 15)
aa

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[7.284662 , 7.8450255],
       [7.597725 , 7.2569847]], dtype=float32)>

In [14]:
tf.norm(aa)                                                                                    

<tf.Tensor: shape=(), dtype=float32, numpy=14.999999>

### Gradient clipping

- Grandient Exploding（gradient值太大，一次前进的步长太大） or vanishing（gradient值太小，一次前进的步长太小）
- set lr=1 （用于出现Grandient Exploding和vanishing）
- new_grads, total_norm = tf.clip_by_global_norm(grads, 25)

[gradient-w1, gradient-w2, ...]，对所有的norm进行等比例缩放