In [1]:
import tensorflow as tf

### where

In [2]:
a = tf.random.normal([3,3])
a

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-1.1811281 ,  1.4865837 , -0.53679025],
       [ 0.89513904,  0.16413315,  0.35710308],
       [ 1.2510114 ,  0.71921575,  1.2408074 ]], dtype=float32)>

In [3]:
mask=a>0
mask

<tf.Tensor: shape=(3, 3), dtype=bool, numpy=
array([[False,  True, False],
       [ True,  True,  True],
       [ True,  True,  True]])>

In [4]:
tf.boolean_mask(a, mask)

<tf.Tensor: shape=(7,), dtype=float32, numpy=
array([1.4865837 , 0.89513904, 0.16413315, 0.35710308, 1.2510114 ,
       0.71921575, 1.2408074 ], dtype=float32)>

In [6]:
indices = tf.where(mask)
indices

<tf.Tensor: shape=(7, 2), dtype=int64, numpy=
array([[0, 1],
       [1, 0],
       [1, 1],
       [1, 2],
       [2, 0],
       [2, 1],
       [2, 2]])>

In [7]:
tf.gather_nd(a, indices)

<tf.Tensor: shape=(7,), dtype=float32, numpy=
array([1.4865837 , 0.89513904, 0.16413315, 0.35710308, 1.2510114 ,
       0.71921575, 1.2408074 ], dtype=float32)>

### where(cond, A, B)

In [8]:
mask

<tf.Tensor: shape=(3, 3), dtype=bool, numpy=
array([[False,  True, False],
       [ True,  True,  True],
       [ True,  True,  True]])>

In [10]:
A = tf.ones([3,3])
A

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [11]:
B = tf.zeros([3, 3])
B

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [12]:
tf.where(mask, A, B)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 1., 0.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

### scatter_nd

```py
tf.scatter_nd(
    indices, 
    updates,
    shape
)
```
> 理解：这方法用于创建tensor？

In [18]:
indices = tf.constant([[4], [3], [1], [7]])
updates = tf.constant([9, 10, 11, 12])
shape = tf.constant([8])
shape

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([8], dtype=int32)>

In [19]:
tf.scatter_nd(indices, updates, shape)

<tf.Tensor: shape=(8,), dtype=int32, numpy=array([ 0, 11,  0, 10,  9,  0,  0, 12], dtype=int32)>

In [24]:
indices = tf.constant([[0], [2]])
updates = tf.constant([
    [
        [5,5,5,5],
        [6,6,6,6],
        [7,7,7,7],
        [8,8,8,8]
    ],
    [
        [5,5,5,5],
        [6,6,6,6],
        [7,7,7,7],
        [8,8,8,8]
    ]    
])
updates.shape

TensorShape([2, 4, 4])

In [22]:
shape = tf.constant([4,4,4])
shape

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([4, 4, 4], dtype=int32)>

In [25]:
tf.scatter_nd(indices, updates, shape)

<tf.Tensor: shape=(4, 4, 4), dtype=int32, numpy=
array([[[5, 5, 5, 5],
        [6, 6, 6, 6],
        [7, 7, 7, 7],
        [8, 8, 8, 8]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[5, 5, 5, 5],
        [6, 6, 6, 6],
        [7, 7, 7, 7],
        [8, 8, 8, 8]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]], dtype=int32)>