In [28]:
import tensorflow as tf
from tensorflow.keras import layers
from tensorflow.keras import Sequential

## 全连接层

### 张量方式实现全连接层

In [29]:
x = tf.random.normal([2, 784])
w1 = tf.Variable(tf.random.truncated_normal([784, 256], stddev=0.1))
b1 = tf.Variable(tf.zeros([256]))
o1 = tf.matmul(x, w1) + b1  # 线性变换
o1 = tf.nn.relu(o1)  # 激活函数
o1


<tf.Tensor: shape=(2, 256), dtype=float32, numpy=
array([[2.1130817 , 2.5407083 , 1.5744436 , 1.2214776 , 0.8052367 ,
        0.8906957 , 0.        , 0.41892922, 0.        , 0.        ,
        0.        , 0.        , 0.73324656, 1.4538964 , 1.6196946 ,
        0.        , 2.0996134 , 0.        , 0.        , 0.        ,
        0.        , 1.9851398 , 0.        , 1.2431812 , 2.0866807 ,
        0.        , 0.79602885, 3.6555233 , 0.        , 0.        ,
        0.        , 0.34293503, 2.1629255 , 2.3206582 , 0.        ,
        0.        , 0.        , 1.2399703 , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        3.685226  , 0.        , 0.74559474, 0.        , 0.2405889 ,
        0.2439518 , 0.9677445 , 0.        , 0.72200465, 3.2210338 ,
        0.        , 0.        , 0.        , 1.6820909 , 0.        ,
        0.19177568, 0.33097625, 0.        , 0.23417406, 2.9687614 ,
        0.        , 0.6390914 , 2.608281  , 0.        , 0.83842504

### 层方式实现全连接层

In [30]:
x = tf.random.normal([4, 28*28])
# 创建全连接层，指定输出节点数和激活函数
fc= layers.Dense(512, activation=tf.nn.relu)
# 通过fc类实例完成一次全连接层的计算，返回输出张量
h1 = fc(x) 
h1


<tf.Tensor: shape=(4, 512), dtype=float32, numpy=
array([[0.        , 0.        , 0.        , ..., 1.9270766 , 0.        ,
        0.        ],
       [0.40866083, 0.        , 0.00809966, ..., 0.96293867, 0.42927146,
        0.        ],
       [0.        , 0.94622374, 0.23846656, ..., 0.        , 0.        ,
        0.        ],
       [1.1736572 , 1.9614882 , 0.7566602 , ..., 0.        , 0.        ,
        0.        ]], dtype=float32)>

In [31]:
# 获取Dense类的权值矩阵(权值张量W)
fc.kernel

<tf.Variable 'dense_1/kernel:0' shape=(784, 512) dtype=float32, numpy=
array([[-0.00267227, -0.00282092, -0.00239151, ..., -0.02661727,
         0.01147866,  0.06112941],
       [ 0.04942616, -0.01818737, -0.06283382, ..., -0.03728904,
         0.01348516, -0.05021691],
       [-0.03163202,  0.06512868, -0.06132587, ...,  0.01436388,
         0.02630632,  0.04413   ],
       ...,
       [-0.05554145,  0.05815712,  0.06551993, ...,  0.02543541,
         0.00813754,  0.03728528],
       [ 0.06328607, -0.04251216,  0.05813259, ...,  0.04935983,
        -0.00627681,  0.04255246],
       [-0.0233203 ,  0.0114582 ,  0.05262707, ..., -0.02605116,
         0.02641326, -0.0292853 ]], dtype=float32)>

In [32]:
# 获取Dense类的偏置向量(偏置张量b)
fc.bias

<tf.Variable 'dense_1/bias:0' shape=(512,) dtype=float32, numpy=
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 

In [33]:
# 获取网硌的所有待优化的张量参数列表，这里为W与b
fc.trainable_variables

# 获取网硌的所有不需要优化的张量参数列表
# fc.non_trainable_variables

# 获取所有参数列表，包含上面两者
# fc.variables

[<tf.Variable 'dense_1/kernel:0' shape=(784, 512) dtype=float32, numpy=
 array([[-0.00267227, -0.00282092, -0.00239151, ..., -0.02661727,
          0.01147866,  0.06112941],
        [ 0.04942616, -0.01818737, -0.06283382, ..., -0.03728904,
          0.01348516, -0.05021691],
        [-0.03163202,  0.06512868, -0.06132587, ...,  0.01436388,
          0.02630632,  0.04413   ],
        ...,
        [-0.05554145,  0.05815712,  0.06551993, ...,  0.02543541,
          0.00813754,  0.03728528],
        [ 0.06328607, -0.04251216,  0.05813259, ...,  0.04935983,
         -0.00627681,  0.04255246],
        [-0.0233203 ,  0.0114582 ,  0.05262707, ..., -0.02605116,
          0.02641326, -0.0292853 ]], dtype=float32)>,
 <tf.Variable 'dense_1/bias:0' shape=(512,) dtype=float32, numpy=
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,

## 神经网络

### 张量方式实现神经网络

In [34]:
# 隐藏层1张量
w1 = tf.Variable(tf.random.truncated_normal([784, 256], stddev=0.1))
b1 = tf.Variable(tf.zeros([256]))

# 隐藏层2张量
w2 = tf.Variable(tf.random.truncated_normal([256, 128], stddev=0.1))
b2 = tf.Variable(tf.zeros([128]))

# 隐藏层3张量
w3 = tf.Variable(tf.random.truncated_normal([128, 64], stddev=0.1))
b3 = tf.Variable(tf.zeros([64]))

# 输出层张量
w4 = tf.Variable(tf.random.truncated_normal([64, 10], stddev=0.1))
b4 = tf.Variable(tf.zeros([10]))

with tf.GradientTape() as tape:  # 梯度记录器
    
    # x: [b, 28*28]
    # 隐藏层1前向计算，[b, 28*28] => [b, 256]
    h1 = x@w1 + tf.broadcast_to(b1, [x.shape[0], 256])
    h1 = tf.nn.relu(h1)

    # 隐藏层2前向计算，[b, 256] => [b, 128]
    h2 = h1@w2 + b2
    h2 = tf.nn.relu(h2)

    # 隐藏层3前向计算，[b, 128] => [b, 64]
    h3 = h2@w3 + b3
    h3 = tf.nn.relu(h3)

    # 输出层前向计算，[b, 64] => [b, 10]
    h4 = h3@w4 + b4

h4


<tf.Tensor: shape=(4, 10), dtype=float32, numpy=
array([[ 1.1116053 ,  0.3521677 , -3.0844083 , -0.4492345 ,  0.02406619,
        -1.3208067 , -0.6864613 ,  1.3855261 ,  1.7404168 ,  1.0428905 ],
       [ 1.3805524 , -0.9140596 , -3.5280728 , -1.7715396 , -0.5988324 ,
        -1.8068151 , -0.80618507,  2.0329604 ,  1.9567118 ,  2.0659328 ],
       [ 0.47052583,  0.44838816, -2.9082556 , -0.3542863 ,  0.14361091,
        -0.89381874,  0.19095016,  0.7630715 ,  1.011778  ,  0.32503614],
       [ 0.42761272, -0.3429447 , -1.0515895 , -0.23576887,  1.1572796 ,
        -0.891214  , -0.93193775,  1.7463063 ,  0.45168707,  0.6394294 ]],
      dtype=float32)>

### 层方式实现神经网络

In [41]:
# 方式一
# 隐藏层1
fc1 = layers.Dense(256, activation=tf.nn.relu)
# 隐藏层2
fc2 = layers.Dense(128, activation=tf.nn.relu)
# 隐藏层3
fc3 = layers.Dense(64, activation=tf.nn.relu)
# 隐藏层
fc4 = layers.Dense(10, activation=None)

x = tf.random.normal([4, 28, 28])
h1 = fc1(x)  # 通过隐藏层1得到输出
h2 = fc2(h1)  # 通过隐藏层2得到输出
h3 = fc3(h2)  # 通过隐藏层3得到输出
h4 = fc4(h3)  # 通过隐藏层4得到输出
h4

<tf.Tensor: shape=(4, 28, 10), dtype=float32, numpy=
array([[[-0.22507548, -0.3335405 ,  0.18823574, ..., -0.5659266 ,
          0.14069253,  0.37929076],
        [-0.07609231, -0.00811549,  0.19692197, ...,  0.15712182,
         -0.00776023, -0.12052844],
        [ 0.02161743,  0.01345335, -0.10942364, ...,  0.13579611,
          0.10823181,  0.02750758],
        ...,
        [ 0.04026046,  0.2355012 ,  0.187748  , ..., -0.02560981,
         -0.2025197 ,  0.1423256 ],
        [-0.38276544, -0.41003254,  0.3780575 , ..., -0.64755726,
          0.02313289,  0.5764718 ],
        [-0.10360569, -0.10879605,  0.01929587, ...,  0.15574111,
         -0.16224623,  0.03080903]],

       [[-0.05802258,  0.10131766,  0.05638222, ...,  0.2514957 ,
         -0.02359182, -0.07964724],
        [-0.02173181,  0.20598564, -0.1934395 , ...,  0.1820691 ,
         -0.11940306, -0.08369346],
        [-0.11748201, -0.07291164,  0.10612024, ...,  0.0209903 ,
          0.04095364,  0.0685025 ],
        ...,
 

In [42]:
# 方式二
model = Sequential([
    # 隐藏层1
    layers.Dense(256, activation=tf.nn.relu),
    # 隐藏层2
    layers.Dense(128, activation=tf.nn.relu),
    # 隐藏层3
    layers.Dense(64, activation=tf.nn.relu),
    # 隐藏层
    layers.Dense(10, activation=None)
])
out = model(x)  # 前向计算得到输出
out

<tf.Tensor: shape=(4, 28, 10), dtype=float32, numpy=
array([[[ 0.18359746,  0.2039048 , -0.30897447, ...,  0.01482356,
         -0.34508723, -0.2538961 ],
        [ 0.4427238 ,  0.34541032, -0.02827301, ...,  0.17581421,
         -0.2104951 , -0.408833  ],
        [ 0.2779747 , -0.26076353, -0.02709447, ...,  0.23210287,
         -0.01470482, -0.10349187],
        ...,
        [ 0.72480965, -0.2286298 ,  0.01073468, ...,  0.24743868,
         -0.18872644, -0.1235151 ],
        [ 0.5499091 ,  0.1371733 , -0.16772051, ..., -0.09394544,
         -0.1465384 ,  0.1599564 ],
        [ 0.5045114 ,  0.00532827, -0.28540537, ...,  0.04006464,
         -0.02622599, -0.27188185]],

       [[ 0.34444043, -0.13919902, -0.16241826, ...,  0.31591365,
         -0.27393425, -0.20587969],
        [ 0.34367603, -0.20802435, -0.11203017, ...,  0.31192982,
         -0.22424948, -0.06286694],
        [ 0.294376  ,  0.20381735, -0.13052092, ...,  0.20241833,
         -0.27694592, -0.08300988],
        ...,
 

### 优化目标

## 激活函数

### Sigmoid
也叫Logistic函数，定义为：

$Sigmoid(x)\stackrel{\mathrm{\Delta}}{=}{\frac{1}{1+e^{-x}}}$

把$x \in R$的输入压缩到$x \in (0,1)$ 区间

In [51]:
x = tf.linspace(-6., 6., 10)
out = tf.nn.sigmoid(x)
out

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([0.00247262, 0.00931596, 0.0344452 , 0.11920292, 0.33924365,
       0.6607564 , 0.880797  , 0.96555483, 0.99068403, 0.9975274 ],
      dtype=float32)>

### ReLU
$ReLU(x)\stackrel{\mathrm{\Delta}}{=}max(0,x)$

x < 0时，返回0

In [54]:
x = tf.linspace(-6., 6., 10)
out = tf.nn.relu(x)
out

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([0.      , 0.      , 0.      , 0.      , 0.      , 0.666667,
       2.      , 3.333334, 4.666667, 6.      ], dtype=float32)>

### LeakyReLU
$LeakyReLU\stackrel{\mathrm{\Delta}}{=}\begin{cases}x, x\geq0,\\px, x<0\end{cases}$

p为用户自行设置的某较小数值的超参数，如0.02等

In [56]:
x = tf.linspace(-6., 6., 10)
out = tf.nn.leaky_relu(x, alpha=0.1)
out

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([-0.6       , -0.46666667, -0.33333334, -0.2       , -0.06666666,
        0.666667  ,  2.        ,  3.333334  ,  4.666667  ,  6.        ],
      dtype=float32)>

### Tanh
$tanh(x) = \frac{(e^x-e^{-x})}{(e^x+e^{-x})}$

= $2 \cdot sigmoid(2x) -1$

将$x \in R$的输入压缩到$(-1,1)$区间，相当于通过Sigmoid函数缩放平移后实现

In [57]:
x = tf.linspace(-6., 6., 10)
out = tf.nn.tanh(x)
out

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([-0.99998784, -0.99982315, -0.9974579 , -0.9640276 , -0.58278286,
        0.58278316,  0.9640276 ,  0.99745804,  0.99982315,  0.99998784],
      dtype=float32)>